name: StudyDuck
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  animated_segmented_tab_control: ^2.0.0
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.3
  connectivity_plus: ^6.1.2
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  easy_localization: ^3.0.7
  envied: ^1.0.0
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  firebase_storage: ^12.4.2
  fl_chart: 0.70.0
  flutter:
    sdk: flutter
  flutter_email_sender: ^6.0.3
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.3
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  go_router: ^14.6.1
  google_mobile_ads: ^5.2.0
  google_sign_in: ^6.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_cropper: ^8.1.0
  image_picker: ^1.1.2
  in_app_review: ^2.0.10
  intl: ^0.19.0
  json_annotation: ^4.9.0
  just_audio: ^0.9.42
  just_audio_background: ^0.0.1-beta.14
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1
  stylish_bottom_bar: ^1.1.0
  url_launcher: ^6.0.6
  uuid: ^4.4.2
  google_mobile_ads: ^5.2.0
  in_app_review: ^2.0.10

dev_dependencies:
  build_runner: ^2.4.13
  change_app_package_name: ^1.4.0
  envied_generator: ^1.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  flutter_oss_licenses: ^3.0.4
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2
  uuid: ^4.4.2

flutter:
  uses-material-design: true

  assets:
    - lib/core/imgs/images/StudyDuck.png
    - lib/core/imgs/icons/
    - lib/core/mp3/
    - lib/core/translations/

  fonts:
    - family: NanumPenScript
      fonts:
        - asset: lib/core/font/NanumPenScript-Regular.ttf
